In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Age': [25, 30, np.nan, 35, 40],
    'Salary': [50000, 60000, 55000, np.nan, 65000],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai']
}

df = pd.DataFrame(data)
df

    Age   Salary     City
0  25.0  50000.0    Delhi
1  30.0  60000.0   Mumbai
2   NaN  55000.0    Delhi
3  35.0      NaN  Chennai
4  40.0  65000.0   Mumbai

In [3]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
df[['Age', 'Salary']] = imputer.fit_transform(df[['Age', 'Salary']])

df

    Age   Salary     City
0  25.0  50000.0    Delhi
1  30.0  60000.0   Mumbai
2  32.5  55000.0    Delhi
3  35.0  57500.0  Chennai
4  40.0  65000.0   Mumbai

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['City_Label'] = le.fit_transform(df['City'])

df

    Age   Salary     City  City_Label
0  25.0  50000.0    Delhi           1
1  30.0  60000.0   Mumbai           2
2  32.5  55000.0    Delhi           1
3  35.0  57500.0  Chennai           0
4  40.0  65000.0   Mumbai           2

In [5]:
df_onehot = pd.get_dummies(df, columns=['City'])
df_onehot

    Age   Salary  City_Label  City_Chennai  City_Delhi  City_Mumbai
0  25.0  50000.0           1         False        True        False
1  30.0  60000.0           2         False       False         True
2  32.5  55000.0           1         False        True        False
3  35.0  57500.0           0          True       False        False
4  40.0  65000.0           2         False       False         True

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[['Age', 'Salary']])

scaled_data

array([[-1.5, -1.5],
       [-0.5,  0.5],
       [ 0. , -0.5],
       [ 0.5,  0. ],
       [ 1.5,  1.5]])

In [7]:
df['Age_Group'] = pd.cut(df['Age'], bins=[20,30,40,50], labels=['Young','Adult','Senior'])
df

    Age   Salary     City  City_Label Age_Group
0  25.0  50000.0    Delhi           1     Young
1  30.0  60000.0   Mumbai           2     Young
2  32.5  55000.0    Delhi           1     Adult
3  35.0  57500.0  Chennai           0     Adult
4  40.0  65000.0   Mumbai           2     Adult

In [8]:
X = df[['Age', 'Salary']]
X

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  32.5  55000.0
3  35.0  57500.0
4  40.0  65000.0